
name: CMake on multiple platforms

on:
  push:
    branches: [ "master", "my_future" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

   env:
  BUILD_DIR: build

steps:
  - uses: actions/checkout@v4

  - name: Configure CMake
    run: cmake -B ${{ env.BUILD_DIR }} -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

  - name: Build
    run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.build_type }}

  - name: Test
    working-directory: ${{ env.BUILD_DIR }}
    run: ctest --build-config ${{ matrix.build_type }}

