name: CMake on multiple platforms

on:
  push:
    branches: [ "master", "my_future" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  MY_VARIABLE: "Hello"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        run: ${{ github.workspace }}/build/MyAwesomeProgram



